dist:
  bionic

language:
  minimal

git:
  depth: false

branches:
  except:
    /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  ./.travis/before_install

install:
  make install

before_script:
  make release

script:
  make build

after_success:
  make linux/binaries

deploy:
  - provider: script
    script: ./linux/packaging/publish
    on:
      branch: master
    skip_cleanup: true
  - provider: script
    script: ./.github/release --tag $(make version)
    on:
      branch: master
    skip_cleanup: true

notifications:
  slack:
    secure: EDmnIfG+m2fa4Ug2ba7BgaV8AFLxV4IOXFaBEr+WWXepjxxeOGAULcONpawJzV+O3pEjsJKzKriBM1cgtatAwRtKFkZs0ohUQcv+l5pXQ4YT+AU1k+goEE7wXAne1BeIylTsUTMTHv1THnpO/8oJ05zgtQXvscSg6cnVwGod9txRBSkCoE+OKIlygyEkpslBIQ/lPCRHlG26nvsaDIYLkonkajVqF6pvZJXBQNa/ZEcuZ7g8ShfOZwconMnz4FfJCkO8FM2RDybnT/ig1jXvvup/SySQeJh/C3/1MpiFUHXlcPMeg6CJWrnu1c03GAxAvEiyDnJ3qtIzBmaROn3OeVEOma4vUFiVlbUStAwaxqLoP9F2pkFZ/wm9qY6pFAEo5vUaBt3UDVsdrMpnOP6PzBThzI4qbzwGnMsCusx3//E+l1lEZ3/MmG/k1re5z+Y4oYsTwTRFieWGGTu2tlawXBnWvJkLSGid2BfweqpuuWvJKW211cl4FHrHrbI/fg212KXApVOcP0E0D3WopjLXdj+waq2p3ub3pg2Tk4Ec0W1K4U99hrB6kSmdVs27f3ofwgUf2RSDH8oo18gKT7ET2SIv/iRhUM9LRdFF9DPAT7OoWxbUppImO+q8fvZpS839uwNELLJ2GqFPMY47ZPOuyHEn70aBSUL+pCvyB7/4E+g=
