#!/usr/bin/env sh
#
# Setup Environment
# Configure Linux Environment
# https://github.com/ashenm/environment
#
# Ashen Gunaratne
# mail@ashenm.ml
#

set -e

# ensure root
test `id -u` -ne 0 && {
  echo >&2 Interactive authentication required!
  exit 1
}

# install bin shims
curl --silent --show-error --output - \
    --url https://github.com/ashenm/environment/releases/latest/download/bin.tar | \
  tar --extract --overwrite --preserve-permissions --file - --directory /

# install sbin shims
curl --silent --show-error --output - \
    --url https://github.com/ashenm/environment/releases/latest/download/sbin.tar | \
  tar --extract --overwrite --preserve-permissions --file - --directory /

# baseimage.sh
curl --silent --show-error \
    --output /etc/profile.d/baseimage.sh \
    --url https://raw.githubusercontent.com/ashenm/baseimage/latest/etc/profile.d/baseimage.sh && \
  chmod 755 /etc/profile.d/baseimage.sh

# workspace.sh
curl --silent --show-error \
    --output /etc/profile.d/workspace.sh \
    --url https://raw.githubusercontent.com/ashenm/workspace/latest/filesystem/etc/profile.d/workspace.sh && \
  chmod 755 /etc/profile.d/workspace.sh

# vimrc
curl --silent --show-error \
    --output /usr/share/vim/vimrc \
    --url https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim && \
  chmod 644 /usr/share/vim/vimrc

# vim ftplugins
mkdir --parent /etc/vim/ftplugin && \
curl --silent --show-error https://github.com/ashenm/workspace/tree/latest/filesystem/etc/vim/ftplugin | \
  grep -oP '/ashenm/workspace/blob/latest/filesystem/etc/vim/ftplugin/\K[^"]{1,}' | while read -r plugin; do
    curl --silent --show-error --output "/etc/vim/ftplugin/$plugin" "https://raw.githubusercontent.com/ashenm/workspace/latest/filesystem/etc/vim/ftplugin/$plugin" && chmod 644 /etc/vim/ftplugin/$plugin
done

# gitconfig
curl --silent --show-error \
    --output /etc/gitconfig \
    --url https://raw.githubusercontent.com/ashenm/workspace/latest/filesystem/etc/gitconfig && \
  chmod 644 /etc/gitconfig

# gitattributes
curl --silent --show-error \
    --output /etc/gitattributes \
    --url https://raw.githubusercontent.com/ashenm/workspace/latest/filesystem/etc/gitattributes && \
  chmod 644 /etc/gitattributes

# ssh client config
test -s /etc/ssh/ssh_config && \
  echo '' | tee -a /etc/ssh/ssh_config >> /dev/null
echo 'Include /etc/ssh/workspace' | \
    tee -a /etc/ssh/ssh_config >> /dev/null && \
  curl --silent --show-error \
    --output /etc/ssh/workspace \
    --url https://raw.githubusercontent.com/ashenm/workspace/latest/filesystem/etc/ssh/workspace && \
  chmod 644 /etc/ssh/workspace

# ensure requisite files
test -f /etc/motd || \
  touch /etc/motd
